source 'https://rubygems.org'

ruby '2.4.6'

gem 'bigdecimal'
gem 'capybara'
gem 'capybara-accessible'
gem 'capybara-click_at'
gem 'chromedriver-helper'
gem 'cucumber'
gem 'cuke_sniffer'
gem 'ffi'
gem 'headless'
gem 'jquery'
gem 'jquery-rails'
gem 'json'
gem 'parallel'
gem 'parallel_tests'
gem 'pony'
gem 'rails'
gem 'rails-dom-testing'
gem 'rake'
gem 'redcarpet'
gem 'report_builder'
gem 'rest-client'
gem 'rspec'
gem 'rspec-retry'
gem 'rubocop'
gem 'screen-recorder', '1.4.0'
gem 'selenium-webdriver'
gem 'streamio-ffmpeg'
gem 'xvfb'
gem 'yard-cucumber'